name: update-ammo-cron
on:
  schedule:
    - cron: '0 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cron to update data store called"
      - name: Call the update API to update data store
        run: |
          curl -X PUT \
          --url 'https://www.tarkov-charts.com/api/ammo' \
          --header 'X-Tarkov-Charts-API-Key: ${{ secrets.TC_API_KEY }}'